### ISSUE TITLE
Bug: PictureDescriptionData Receives Tuple Instead of String (picture_description_api with custom API endpoint causes ValidationError)

### ISSUE THREAD

**Issue by Ulli2060** [docling-project/docling-serve#438]
## Problem

Using `picture_description_api` with custom API endpoint causes ValidationError:

```
ValidationError: 1 validation error for DescriptionAnnotation
text
  Input should be a valid string [type=string_type, input_value=('The image shows a colla...', 439), input_type=tuple]
```

## Reproduction

```json
{
  "options": {
    "pipeline": "standard",
    "do_picture_description": true,
    "picture_description_api": {
      "url": "https://<ENDPOINT>/chat/completions",
      "headers": {"api-key": "<KEY>"},
      "prompt": "Describe the image."
    }
  },
  "sources": [{"kind": "file", "filename": "test.pdf", "base64_string": "..."}]
}
```

## Stack Trace

```python
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.12/site-packages/rq/worker.py", line 1659, in perform_job
    return_value = job.perform()
  File "/opt/app-root/lib64/python3.12/site-packages/rq/job.py", line 1318, in perform
    self._result = self._execute()
  File "/opt/app-root/lib64/python3.12/site-packages/rq/job.py", line 1376, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/opt/app-root/lib64/python3.12/site-packages/docling_jobkit/orchestrators/rq/worker.py", line 178, in docling_task
    raise e
  File "/opt/app-root/lib64/python3.12/site-packages/docling_jobkit/orchestrators/rq/worker.py", line 141, in docling_task
    processed_results = process_export_results(
  File "/opt/app-root/lib64/python3.12/site-packages/docling_jobkit/convert/results.py", line 163, in process_export_results
    conv_results = list(conv_results)
  File "/opt/app-root/lib64/python3.12/site-packages/docling/document_converter.py", line 260, in convert_all
    for conv_res in conv_res_iter:
  File "/opt/app-root/lib64/python3.12/site-packages/docling/document_converter.py", line 332, in _convert
    for item in map(
  File "/opt/app-root/lib64/python3.12/site-packages/docling/document_converter.py", line 379, in _process_document
    conv_res = self._execute_pipeline(in_doc, raises_on_error=raises_on_error)
  File "/opt/app-root/lib64/python3.12/site-packages/docling/document_converter.py", line 402, in _execute_pipeline
    conv_res = pipeline.execute(in_doc, raises_on_error=raises_on_error)
  File "/opt/app-root/lib64/python3.12/site-packages/docling/pipeline/base_pipeline.py", line 80, in execute
    raise e
  File "/opt/app-root/lib64/python3.12/site-packages/docling/pipeline/base_pipeline.py", line 75, in execute
    conv_res = self._enrich_document(conv_res)
  File "/opt/app-root/lib64/python3.12/site-packages/docling/pipeline/base_pipeline.py", line 110, in _enrich_document
    for element in model(
  File "/opt/app-root/lib64/python3.12/site-packages/docling/models/picture_description_base_model.py", line 84, in __call__
    PictureDescriptionData(text=output, provenance=self.provenance)
  File "/opt/app-root/lib64/python3.12/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for DescriptionAnnotation
text
  Input should be a valid string [type=string_type, input_value=('The image shows a colla...tch explanations.', 439), input_type=tuple]
```

**Error**: `output` is tuple `(str, int)` but should be `str`.

## Fix

**File**: `docling/models/picture_description_base_model.py:82-84`

```python
for item, output in zip(elements, outputs):
    text_value = output[0] if isinstance(output, tuple) else output
    item.annotations.append(
        PictureDescriptionData(text=text_value, provenance=self.provenance)
    )
```

## Environment
- docling-serve v1.8.0 (container) 
- Custom API endpoint (Azure OpenAI)

**Comment by geneives233** [comment]
Using vllm also encounters this issue.

**Comment by jkesler-nlign** [comment]
I've been trying to get Docling working with our internal vLLM and Open WebUI instances today and have been doing some digging. I believe this issue was introduced a few weeks ago in [this](https://github.com/docling-project/docling/commit/b6c892b505bf29a12ce7e8d9b4e88e1253440ebc) commit to docling. Reverting to docling-serve v1.7.1 which includes docling 2.58.0 resolved the issue for me

**Comment by Ulli2060** [comment]
I can confirm this behaviour. After reviewing the recent changes in docling/docling-serve, it looks like the issue was introduced when the LLM/VLM temperature option was added (around v1.7.2). The core logic was updated, but the corresponding Pydantic request models for picture_description_api and vlm_pipeline_model_api were not adjusted.

As a result, these endpoints now receive values that can be returned as tuples (e.g. (text, token_count) or other structured outputs), while the Pydantic models still strictly expect plain strings. This mismatch explains why the validator fails with “tuple received instead of string”. Downgrading to docling-serve v1.7.1 works because this regression was introduced shortly after.

A fix would be to update the Pydantic models for these APIs to accept the new output structure or normalize the values before validation.

See docling fix 
https://github.com/docling-project/docling/issues/2550

**Comment by dolfim-ibm** [comment]
The `:main` image is now using the new Docling version. Is the issue resolved?

**Comment by Ulli2060** [comment]
@dolfim-ibm Confirmed working with Azure OpenAI (docling-serve 1.9.0, :main image). Both picture_description_api and vlm_pipeline_model_api now work correctly. Thanks for the quick fix

**Comment by erdenizayd** [comment]
The problem is still present in :main and :latest images. When "pipeline" is set to "vlm" and "vlm_pipeline_model_api" is provided, image files cause "'VlmPipelineOptions' object has no attribute 'ocr_options'" error. v1.7.1 image has no problem.

The example provided in this issue sets the "pipeline" option to "standard", which results in docling-serve to load the default ocr model rather than sending the request to provided vlm api.
